### ISSUE TITLE
CI: Ubuntu Groovy failing

### ISSUE THREAD

**Issue by solardiz** [lkrg-org/lkrg#132] opened 2021-12-29 01:10 UTC
We started getting this:

```
I: Retrieving InRelease 
I: Retrieving Release 
E: Failed getting release file http://archive.ubuntu.com/ubuntu/dists/groovy/Release
‣ Detaching namespace
‣ Setting up package cache…
‣ Setting up package cache /home/runner/work/lkrg/lkrg/mkosi.cache complete
‣ Setting up temporary workspace.
‣ Temporary workspace set up in /var/tmp/mkosi-h726qpf8
‣ Running first (development) stage…
‣  Creating image with partition table…
‣  Created image with partition table as /home/runner/work/lkrg/lkrg/.mkosi-j5lzdb18
‣  Attaching /home/runner/work/lkrg/lkrg/.mkosi-j5lzdb18 as loopback…
‣  Attached /dev/loop3
‣  Formatting root partition…
‣  Mounting image…
‣  Setting up basic OS tree…
‣  Mounting Package Cache
‣  Installing Ubuntu…
‣  (Unmounting Package Cache)
‣  (Unmounting image)
‣  (Detaching /dev/loop3)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__main__.py", line 32, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__main__.py", line 26, in main
    run_verb(a)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 7812, in run_verb
    manifest = build_stuff(args)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 7222, in build_stuff
    image = build_image(args, root, do_run_build_script=True)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 6968, in build_image
    install_distribution(args, root, do_run_build_script, cached_tree)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 3115, in install_distribution
    install[args.distribution](args, root, do_run_build_script)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 2769, in install_ubuntu
    install_debian_or_ubuntu(args, root, do_run_build_script=do_run_build_script)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 2678, in install_debian_or_ubuntu
    run(cmdline)
  File "/usr/local/lib/python3.8/dist-packages/mkosi/backend.py", line 693, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['debootstrap', '--variant=minbase', '--merged-usr', '--components=universe,main', 'groovy', '/var/tmp/mkosi-h726qpf8/root', 'http://archive.ubuntu.com/ubuntu']' returned non-zero exit status 1.
Error: Process completed with exit code 1.
```

I think I'll try "repairing" this by:

```diff
+++ b/.github/workflows/mkosi-boot.yml
@@ -10,7 +10,6 @@ jobs:
             matrix:
                 release:
                     - focal
-                    - groovy
                     - hirsute
         steps:
             - uses: actions/checkout@v2
```

**Comment by solardiz** [comment] 2021-12-29 01:43
@vt-alt When you have a moment, please take a look and maybe re-introduce testing on Groovy or just close this issue. Thanks.

**Comment by vt-alt** [comment] 2021-12-30 09:57
`groovy` seems to be short life-cycle release and only could be deleted (or upgraded to `hirsute` which we already have, but it will EOL in 01/2022). We can add some another release. `impish` looks good.

https://wiki.ubuntu.com/Releases

**Comment by vt-alt** [comment] 2021-12-30 11:02
Maybe we should generalize list of testable Ubuntu-s, I think this should be possible,

**Comment by solardiz** [comment] 2021-12-30 14:43
Why can't we continue testing on a EOL'ed version of Ubuntu? Maybe we can fix something to make that work?

> Maybe we should generalize list of testable Ubuntu-s

Do you mean having it automatically generated/updated? I'm not sure that's what we want. However, we should somehow be adding new versions.

**Comment by vt-alt** [comment] 2021-12-30 14:59
> Do you mean having it automatically generated/updated? I'm not sure that's what we want. However, we should somehow be adding new versions.

To me this sounds somehow contradictory.

> Maybe we can fix something to make that work?

I'll check if mkosi can work with this http://old-releases.ubuntu.com/ubuntu/dists/

How long do you plan to support groovy?

ps. Also, we can move it to build-only test in Docker (in `builds.yml`).

**Comment by vt-alt** [comment] 2021-12-30 15:04
> How long do you plan to support groovy?

I understand that _longer is better_, but there is long term releases and short term releases. Perhaps reasonable users who want to sit on the same old release for a long will at least use long term release like `focal` (which is boot tested).

**Comment by solardiz** [comment] 2021-12-30 15:13
Not updating the Ubuntu versions list automatically yet wanting to promptly add new versions is in fact contradictory, however my thinking is we don't want (more) sudden CI failures on unrelated changes to LKRG. When we explicitly add a new version of Ubuntu, we expect possible failure due to that and we can handle it on a pull request intended for just that.

Our testing on older versions isn't only to support those specific distros/versions, but also to have LKRG tested with those kernel versions, where similar versions might also be used on other distros from the time, including non-EOL'ed ones. The oldest we currently support is RHEL7, so I think we should also keep support for any distro that we currently support and that is newer than RHEL7, even if it gets EOL'ed. For Ubuntu, we claimed support for 16.04+, and I think we should keep it that way for now.

We can indeed be dropping support for EOL'ed distros, but I'd rather do this for specific good reasons (if keeping such support becomes difficult or conflicts with our other goals), not just because of their EOL.

**Comment by vt-alt** [comment] 2021-12-30 15:31
I just noticed that groovy is completely deleted even from old-releases and that http://old-releases.ubuntu.com/ubuntu/dists/groovy/ is 404'd. So I don't see how can fix it, at least until they provide it somewhere. (Perhaps they will.)

> Not updating the Ubuntu versions list automatically yet wanting to promptly add new versions is in fact contradictory, however my thinking is we don't want (more) sudden CI failures on unrelated changes to LKRG. When we explicitly add a new version of Ubuntu, we expect possible failure due to that and we can handle it on a pull request intended for just that.

Isn't you can always ignore failure for an unrelated commit if you see that it's new Ubuntu release just appeared? 

Well, I don't see it now for lkrg, but other projects have full CI results table on the bottom of every pull request, so it's visible which test is failed in case it's not all green.

**Comment by vt-alt** [comment] 2021-12-30 15:34
> I just noticed that groovy is completely deleted even from old-releases and that http://old-releases.ubuntu.com/ubuntu/dists/groovy/ is 404'd.

This fixed quickly.

**Comment by vt-alt** [comment] 2021-12-30 15:37
What would be good in autogeneated Ubuntu dists list is we don't need to follow what and when they release (I personally don't follow this). But there could be failures like this with groovy (when it suddenly disappeared) So it's trade off. Well, if you don't want I will not try to implement it.

**Comment by vt-alt** [comment] 2021-12-30 15:39
> > I just noticed that groovy is completely deleted even from old-releases and that http://old-releases.ubuntu.com/ubuntu/dists/groovy/ is 404'd.
> 
> This got fixed quickly.

No it's more complicated. Sometimes its 404, sometimes visible.

**Comment by solardiz** [comment] 2021-12-30 15:42
For now, I think let's keep Groovy removed and you add new version(s) manually. However, I'm open to revisiting this discussion and possibly doing things differently later. Thank you!

**Comment by vt-alt** [comment] 2021-12-30 20:21
[Now I'm not sure there was ever 404 since I realized I messed URLs. Anyway.] `mkosi -m http://old-releases.ubuntu.com/ubuntu/ -r groovy` works and I can fix CI.

**Comment by vt-alt** [comment] 2021-12-30 21:08
> Now I'm not sure there was ever 404

No I'm certain now there is 404 sometimes. Excuse me for the noise, it was driving me crazy too.

**Comment by vt-alt** [comment] 2022-01-01 19:40
Filed a bug https://bugs.launchpad.net/ubuntu/+bug/1956164

**Comment by solardiz** [comment] 2022-01-13 13:15
@vt-alt No replies to that launchpad bug entry yet, but I cannot reproduce the 404 now - can you? Thanks!

**Comment by vt-alt** [comment] 2022-01-13 22:40
```
root@ubuntu-impish:~# curl -v -I http://old-releases.ubuntu.com/ubuntu/dists/groovy/
*   Trying 91.189.91.123:80...
* Connected to old-releases.ubuntu.com (91.189.91.123) port 80 (#0)
> HEAD /ubuntu/dists/groovy/ HTTP/1.1
> Host: old-releases.ubuntu.com
> User-Agent: curl/7.74.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
HTTP/1.1 404 Not Found
< Date: Thu, 13 Jan 2022 22:39:57 GMT
Date: Thu, 13 Jan 2022 22:39:57 GMT
< Server: Apache/2.4.29 (Ubuntu)
Server: Apache/2.4.29 (Ubuntu)
< Content-Type: text/html; charset=iso-8859-1
Content-Type: text/html; charset=iso-8859-1
```

**Comment by vt-alt** [comment] 2022-01-17 05:12
Still not fixed. Maybe we should add Ubuntu 22.04 Jammy Jellyfish instead?

> Canonical's latest iteration to the Ubuntu operating system is Ubuntu 22.04 Jammy Jellyfish, scheduled for release on April 21, 2022. This is an LTS (long term support) release – the type of release that Canonical only publishes every two years, and continues to support for the next five.3

**Comment by Adam-pi3** [comment] 2022-02-22 01:10
Looks like the issue is still there and we are not the only one affected by it:
https://bugs.launchpad.net/ubuntu/+bug/1956164/comments/4

@vt-alt yes, we should add 22.04 additionally to groovy. @solardiz what do you think?

**Comment by vt-alt** [comment] 2022-02-22 01:33
22.04 is [jammy](https://github.com/lkrg-org/lkrg/commit/e54ed31839e50363470a53124b667b31ed596248). 
https://wiki.ubuntu.com/Releases

**Comment by Adam-pi3** [comment] 2022-02-22 05:23
@vt-alt yep, that's what I meant. We should NOT remove `groovy` and at the same time we should add 22.04 (`jammy`). Sorry for confusion

**Comment by vt-alt** [comment] 2022-02-22 05:27
Upstream repo for groovy does not work and is deleted from all mirrors. How could we not remove it? And how we can add jammy if it's already added?

**Comment by Adam-pi3** [comment] 2022-02-22 06:02
@vt-alt I'm aware it is not working for now (see my previous comments), but the bug which you opened is not closed and because we are not the only one who encounter this problem I hope it will be fixed. When this happens, we should reenable `groovy`.

Thanks for adding `jammy` - I was not aware it is already added.

**Comment by Adam-pi3** [comment] 2022-02-22 16:00
@vt-alt I would be thankful if you shed some more light on what `mkosi` verifies. I can see in that file `https://github.com/lkrg-org/lkrg/blob/main/.github/workflows/mkosi-boot.yml`:
```
            matrix:
                release:
                    - focal
                    - hirsute
                    - jammy
```
But I don't see `Bionic` which is visible here `https://github.com/lkrg-org/lkrg/blob/main/.travis.yml`. Should we add `Bionic` to `mkosi` as well?

**Comment by solardiz** [comment] 2022-02-22 18:29
BTW, we're seeing many CI failures with QEMU reporting "hardware error". I sometimes have to re-run jobs a few times until we get all-green again. Maybe this means we're already close to or beyond the maximum resource usage we can have on GitHub.

**Comment by vt-alt** [comment] 2022-02-22 19:19
> shed some more light on what `mkosi` verifies.

What do you mean? `mkosi` builds bootable disk image. and then also boot it in qemu. With this we verify that lkrg does not hang the system straight away on the boot.

Docker builds just `make` lkrg for their corresponding distribution kernels, but don't boot them. So it only verifies ability to build.

**Comment by vt-alt** [comment] 2022-02-22 19:24
> BTW, we're seeing many CI failures with QEMU reporting "hardware error". I sometimes have to re-run jobs a few times until we get all-green again. Maybe this means we're already close to or beyond the maximum resource usage we can have on GitHub.

https://github.com/lkrg-org/lkrg/runs/5259672421?check_suite_focus=true
Seems to be even before Linux boot "KVM: entry failed, hardware error 0xffffffff".

**Comment by vt-alt** [comment] 2022-02-22 19:31
> Seems to be even before Linux boot "KVM: entry failed, hardware error 0xffffffff".

As I remember there is not KVM on github actions, so it should not even try enter KVM. Possible there is some misconfigured GA workers, need investigate further.

**Comment by Adam-pi3** [comment] 2022-02-22 19:36
@vt-alt Thanks. Can we add Bionic to `mkosi` as well?

**Comment by vt-alt** [comment] 2022-02-22 19:43
As I remember there was [some problems with  bionic](https://github.com/lkrg-org/lkrg/pull/61) but maybe they are gone already. I will look again.

**Comment by vt-alt** [comment] 2022-02-22 19:46
> Possible there is some misconfigured GA workers (which detected as KVM capable but really aren't), need investigate further.

Maybe we should report to [upstream ](https://github.com/actions/virtual-environments).

> Maybe this means we're already close to or beyond the maximum resource usage we can have on GitHub.

@solardiz Is there any stat on this?

**Comment by vt-alt** [comment] 2022-02-22 20:09
> need investigate further.

Looking more attentively I see on failed build qemu parameters:
* qemu-system-x86_64 -machine type=q35,**accel=kvm**,smm=off -smp 2 -m 1G ... -cpu host ...

And on successful:
* qemu-system-x86_64 -machine type=q35,**accel=tcg**,smm=off -smp 2 -m 1G ...

So mkosi decides it should be kvm, but there are obviously no kvm on GA.
```
mkosi (main)$ git grep -e has_kvm -e accel
mkosi/__init__.py:    has_kvm = os.path.exists("/dev/kvm")
mkosi/__init__.py:    accel = "kvm" if has_kvm else "tcg"
mkosi/__init__.py:        f"type=q35,accel={accel},smm={'on' if fw_supports_sb else 'off'}",
mkosi/__init__.py:    if has_kvm:
```
I don't see options to control this, perhaps we shall do `rm -f "/dev/kvm` before mkosi run.

**Comment by vt-alt** [comment] 2022-02-22 20:27
BTW, `hirsute` is EOL'ed @ January 20, 2022, so I'd expect its fate similar to `groovy` anytime soon.

**Comment by Adam-pi3** [comment] 2022-02-22 20:46
@vt-alt `/dev/kvm` exists if there is an installed a KVM driver which supports hardware virtualization. I'm not sure if removing it (you would need `rmmod kvm`  instead of `rm -f`) won't break the test. QEMU should still be able to run in emulation mode.

**Comment by vt-alt** [comment] 2022-02-22 20:55
Device could be created manually with `mknod` w/o even presence of the driver, in that case opening it will return `ENODEV`. 
QEMU may run in emulated mode w/o kvm if it's allowed with command line option like `-M accel=kvm:tcg` in that case it will fallback to tcg if there is no kvm. But mkosi does not pass `tcg` there so it just fails.
I am quite familiar with all this because I'm doing virtme-like qemu runner for ALT: https://github.com/vt-alt/rpm-build-vm

**Comment by solardiz** [comment] 2022-02-22 21:33
> @solardiz Is there any stat on this?

Not really, but I think this started occurring within the recent 2 weeks, and the other day I had to restart a job 3 or 4 times until all builds succeeded. Also, IIRC on one occasion I saw QEMU report a "hardware error" not right away, but at some point after some messages from the guest Linux kernel - but most of the time it's right away, as you noticed.

**Comment by vt-alt** [comment] 2022-02-22 21:36
Maybe they experimenting with KVM but it's definitely not working now. I will submit PR with a fix.

**Comment by vt-alt** [comment] 2022-02-23 21:04
> Also, IIRC on one occasion I saw QEMU report a "hardware error" not right away, but at some point after some messages from the guest Linux kernel - but most of the time it's right away, as you noticed.

Wow this makes things really hard to understand, I found relevant logs (just for the record):

https://github.com/lkrg-org/lkrg/runs/5251323060?check_suite_focus=true
https://github.com/lkrg-org/lkrg/runs/5251322870?check_suite_focus=true

**Comment by vt-alt** [comment] 2022-02-23 21:24
> Maybe we should report to [GA upstream ](https://github.com/actions/virtual-environments).

Reported in issue 5128.

**Comment by vt-alt** [comment] 2022-02-27 17:42
JFYI: I tried to reproduce, but it does not. https://github.com/vt-alt/kvm_on_ga_tests/actions/workflows/test.yml

**Comment by vt-alt** [comment] 2023-05-03 23:36
> Filed a bug https://bugs.launchpad.net/ubuntu/+bug/1956164

(Update.) They replied today.

> Paul White (paulw2u) wrote 15 hours ago:
> Bug reports filed against 'Ubuntu' without designating a package seldom attract any immediate attention.
> However, this was definitely the wrong place to report this problem. I'm not sure but https://github.com/canonical/ubuntu.com/issues/new seems a good place to report problems against ubuntu.com websites.
> I'll close this as being 'Invalid'. If this is still an issue with any old release please use the link above to report the problem.

**Comment by solardiz** [comment] 2023-05-19 12:25
@vt-alt Do you think we should simply close this issue or try re-enabling `groovy` (maybe it just works now)? Please feel free to proceed either way. Thank you!

**Comment by vt-alt** [comment] 2023-05-19 12:32
Closing is simpler, but I don't have close button.

**Closed** 2023-05-19 12:50 UTC
Labels: testing
